# Generated by Django 4.2 on 2024-02-14 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("basic_info", "0002_alter_schoolinfo_basic_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="basic_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_experience",
                to="basic_info.mybasicinfo",
            ),
        ),
    ]
